context:
  version: "0.23.0"

package:
  name: manypkg
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@manypkg/cli/-/cli-${{ version }}.tgz
  sha256: 98d1c6ed594f426b50030cc30c8f53487ea6812e94205d44be8ae4f7fc79234a

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "manypkg 2>&1 | grep -q \"command undefined not found, only check, exec, run, upgrade, npm-tag and fix exist\""

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: An umbrella for your monorepo
  homepage: https://github.com/Thinkmill/manypkg
  repository: https://github.com/Thinkmill/manypkg

extra:
  recipe-maintainers:
    - danielnachun
