context:
  version: "0.24.0"

package:
  name: manypkg
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@manypkg/cli/-/cli-${{ version }}.tgz
  sha256: 23e56c7b7d7332adcd2279cc767fe1303f800fff23cf690ef684c411d0965a00

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "manypkg 2>&1 | grep -q \"command undefined not found, only check, exec, run, upgrade, npm-tag and fix exist\""

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: An umbrella for your monorepo
  homepage: https://github.com/Thinkmill/manypkg
  repository: https://github.com/Thinkmill/manypkg

extra:
  recipe-maintainers:
    - danielnachun
