context:
  version: 0.21.4

package:
  name: manypkg
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@manypkg/cli/-/cli-${{ version }}.tgz
  sha256: 8cf668d21728b2a466914fbdfcd75e3dff82d9124d10bf82620377ac4b2f7c08

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "manypkg 2>&1 | grep -q \"command undefined not found, only check, exec, run, upgrade, npm-tag and fix exist\""

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: An umbrella for your monorepo
  homepage: https://github.com/Thinkmill/manypkg
  repository: https://github.com/Thinkmill/manypkg

extra:
  recipe-maintainers:
    - danielnachun
